-- ============================================================
-- IGNEA LABS — Seed Solutions Data
-- 3 solutions per industry per stream + 1 generic per stream
-- Run AFTER schema.sql
-- ============================================================

-- ============================================================
-- GENERIC (fallback for industries without specific solutions)
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

-- Generic: customerFlow
('generic', 'customerFlow',
 'Bot de Atención al Cliente con IA',
 'AI Customer Service Bot',
 'Respuesta automática 24/7 a consultas frecuentes por WhatsApp y web. Reduce tiempo de respuesta de horas a segundos y libera a tu equipo para tareas de mayor valor.',
 '24/7 automatic response to frequent inquiries via WhatsApp and web. Reduces response time from hours to seconds and frees your team for higher-value tasks.',
 '2-3', 0.35, 1),

-- Generic: operationsFlow
('generic', 'operationsFlow',
 'Automatización de Procesos Operativos',
 'Operations Process Automation',
 'Elimina tareas manuales repetitivas — inventario, agenda, reportes, facturación. Tu equipo recupera horas cada semana para enfocarse en lo que genera ingresos.',
 'Eliminates repetitive manual tasks — inventory, scheduling, reports, billing. Your team recovers hours each week to focus on revenue-generating work.',
 '3-5', 0.40, 1),

-- Generic: informationFlow
('generic', 'informationFlow',
 'Dashboard de Datos en Tiempo Real',
 'Real-Time Data Dashboard',
 'Visibilidad completa de tu operación en un solo lugar. Métricas clave actualizadas automáticamente para tomar decisiones basadas en datos, no en intuición.',
 'Complete visibility of your operation in one place. Key metrics automatically updated for data-driven decisions, not gut feelings.',
 '2-3', 0.25, 1),

-- Generic: growthFlow
('generic', 'growthFlow',
 'Infraestructura de Escalabilidad',
 'Scalability Infrastructure',
 'Sistemas que crecen contigo. Automatización de onboarding, procesos estandarizados y capacidad operativa que escala sin agregar personal proporcionalmente.',
 'Systems that grow with you. Automated onboarding, standardized processes, and operational capacity that scales without proportionally adding headcount.',
 '4-6', 0.20, 1);


-- ============================================================
-- RESTAURANT
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

-- Restaurant: customerFlow
('restaurant', 'customerFlow',
 'Bot de Reservaciones y Pedidos con IA',
 'AI Reservations & Orders Bot',
 'Reservaciones automáticas, pedidos para llevar y respuesta a preguntas frecuentes por WhatsApp 24/7. Reduce llamadas perdidas y libera al personal de hostess.',
 'Automatic reservations, takeout orders, and FAQ responses via WhatsApp 24/7. Reduces missed calls and frees up your host staff.',
 '2-3', 0.35, 1),
('restaurant', 'customerFlow',
 'Sistema de Feedback y Reseñas Automatizado',
 'Automated Feedback & Reviews System',
 'Encuestas post-visita automáticas, gestión de reseñas en Google/Yelp y seguimiento de satisfacción. Convierte clientes satisfechos en promotores activos.',
 'Automatic post-visit surveys, Google/Yelp review management, and satisfaction tracking. Turns satisfied customers into active promoters.',
 '1-2', 0.15, 2),
('restaurant', 'customerFlow',
 'Menú Digital Interactivo con Upselling',
 'Interactive Digital Menu with Upselling',
 'Menú digital con fotos, alérgenos y sugerencias inteligentes de maridaje o postres. Aumenta ticket promedio un 12-18% sin esfuerzo del mesero.',
 'Digital menu with photos, allergens, and smart pairing/dessert suggestions. Increases average ticket by 12-18% without waiter effort.',
 '1-2', 0.12, 3),

-- Restaurant: operationsFlow
('restaurant', 'operationsFlow',
 'Automatización de Inventario y Proveedores',
 'Inventory & Supplier Automation',
 'Control automático de inventario, alertas de reorden y comunicación con proveedores. Elimina el conteo manual y reduce desperdicio de alimentos.',
 'Automatic inventory tracking, reorder alerts, and supplier communication. Eliminates manual counting and reduces food waste.',
 '3-4', 0.40, 1),
('restaurant', 'operationsFlow',
 'Gestión Inteligente de Turnos y Personal',
 'Smart Shift & Staff Management',
 'Programación automática de turnos basada en demanda histórica, gestión de cambios y control de horas. Reduce sobrestaff en horas muertas.',
 'Automatic shift scheduling based on historical demand, swap management, and hours tracking. Reduces overstaffing during slow hours.',
 '2-3', 0.20, 2),
('restaurant', 'operationsFlow',
 'Control de Calidad y Recetas Estandarizadas',
 'Quality Control & Standardized Recipes',
 'Sistema digital de recetas con costos por porción, checklists de preparación y control de temperaturas. Consistencia en cada plato, cada turno.',
 'Digital recipe system with per-portion costs, prep checklists, and temperature monitoring. Consistency in every dish, every shift.',
 '2-3', 0.15, 3),

-- Restaurant: informationFlow
('restaurant', 'informationFlow',
 'Dashboard de Ventas y Costos de Alimentos',
 'Sales & Food Cost Dashboard',
 'Visibilidad en tiempo real de ventas por plato, food cost, horas pico y rendimiento del personal. Decisiones de menú basadas en datos reales.',
 'Real-time visibility into sales by dish, food cost, peak hours, and staff performance. Menu decisions based on actual data.',
 '2-3', 0.25, 1),
('restaurant', 'informationFlow',
 'Análisis de Desperdicio y Merma',
 'Waste & Shrinkage Analytics',
 'Seguimiento automático de desperdicio por ingrediente, identificación de patrones de merma y alertas de desviación. Reduce food waste un 20-30%.',
 'Automatic waste tracking by ingredient, shrinkage pattern identification, and deviation alerts. Reduces food waste by 20-30%.',
 '1-2', 0.18, 2),
('restaurant', 'informationFlow',
 'Reportes de Rentabilidad por Plato',
 'Per-Dish Profitability Reports',
 'Análisis automático de margen por plato considerando ingredientes, tiempo de preparación y popularidad. Identifica qué platos mantener, modificar o eliminar.',
 'Automatic margin analysis per dish considering ingredients, prep time, and popularity. Identifies which dishes to keep, modify, or remove.',
 '1-2', 0.15, 3),

-- Restaurant: growthFlow
('restaurant', 'growthFlow',
 'Sistema de Fidelización y Marketing Automatizado',
 'Loyalty & Automated Marketing System',
 'Programa de lealtad digital, campañas automáticas por WhatsApp y seguimiento de clientes recurrentes para maximizar lifetime value.',
 'Digital loyalty program, automated WhatsApp campaigns, and recurring customer tracking to maximize lifetime value.',
 '4-6', 0.20, 1),
('restaurant', 'growthFlow',
 'Delivery y E-commerce Propio',
 'Own Delivery & E-commerce',
 'Plataforma propia de pedidos en línea sin comisiones de terceros. Integrada con tu menú, inventario y sistema de delivery.',
 'Own online ordering platform without third-party commissions. Integrated with your menu, inventory, and delivery system.',
 '4-6', 0.22, 2),
('restaurant', 'growthFlow',
 'Expansión Multi-Local con Estándares',
 'Multi-Location Expansion with Standards',
 'Sistemas centralizados de operación para manejar múltiples locales: menú unificado, inventario consolidado y reportería comparativa.',
 'Centralized operating systems for managing multiple locations: unified menu, consolidated inventory, and comparative reporting.',
 '6-8', 0.15, 3);


-- ============================================================
-- MEDICAL
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

('medical', 'customerFlow',
 'Sistema de Citas y Triage con IA',
 'AI Appointments & Triage System',
 'Agendamiento automático, recordatorios de citas y pre-triage inteligente por WhatsApp. Reduce no-shows y optimiza la agenda del médico.',
 'Automatic scheduling, appointment reminders, and intelligent pre-triage via WhatsApp. Reduces no-shows and optimizes the doctor''s schedule.',
 '3-4', 0.30, 1),
('medical', 'customerFlow',
 'Comunicación Post-Consulta Automatizada',
 'Automated Post-Visit Communication',
 'Seguimiento automático de pacientes post-consulta, recordatorios de medicamentos y encuestas de satisfacción. Mejora adherencia al tratamiento.',
 'Automatic post-visit patient follow-up, medication reminders, and satisfaction surveys. Improves treatment adherence.',
 '2-3', 0.15, 2),
('medical', 'customerFlow',
 'Portal de Pre-Registro Digital',
 'Digital Pre-Registration Portal',
 'Formularios de admisión digitales, historial médico previo a la cita y consentimientos electrónicos. Reduce tiempo en sala de espera un 40%.',
 'Digital admission forms, pre-visit medical history, and electronic consents. Reduces waiting room time by 40%.',
 '2-3', 0.20, 3),

('medical', 'operationsFlow',
 'Automatización de Expedientes y Facturación',
 'Records & Billing Automation',
 'Digitalización de expedientes, facturación automatizada a planes médicos y seguimiento de cobros. Reduce errores administrativos y acelera pagos.',
 'Digitized medical records, automated insurance billing, and collections tracking. Reduces administrative errors and accelerates payments.',
 '4-6', 0.35, 1),
('medical', 'operationsFlow',
 'Gestión de Inventario Médico',
 'Medical Inventory Management',
 'Control automático de suministros médicos, medicamentos y equipos. Alertas de vencimiento, reorden automático y seguimiento de costos por procedimiento.',
 'Automatic control of medical supplies, medications, and equipment. Expiration alerts, auto-reorder, and per-procedure cost tracking.',
 '3-4', 0.20, 2),
('medical', 'operationsFlow',
 'Coordinación de Laboratorio y Resultados',
 'Lab Coordination & Results',
 'Integración automática con laboratorios, entrega digital de resultados y alertas de valores críticos. Reduce tiempo de diagnóstico y llamadas de seguimiento.',
 'Automatic lab integration, digital results delivery, and critical value alerts. Reduces diagnosis time and follow-up calls.',
 '4-6', 0.18, 3),

('medical', 'informationFlow',
 'Dashboard Clínico y Financiero',
 'Clinical & Financial Dashboard',
 'Métricas de pacientes atendidos, tiempos de espera, ingresos por servicio y eficiencia operativa. Datos clínicos y financieros en un solo lugar.',
 'Metrics on patients seen, wait times, revenue per service, and operational efficiency. Clinical and financial data in one place.',
 '3-4', 0.25, 1),
('medical', 'informationFlow',
 'Análisis de Patrones de Pacientes',
 'Patient Pattern Analytics',
 'Identificación de tendencias de diagnóstico, estacionalidad de consultas y análisis de población atendida. Planificación basada en datos epidemiológicos locales.',
 'Diagnosis trend identification, consultation seasonality, and patient population analysis. Planning based on local epidemiological data.',
 '3-4', 0.15, 2),
('medical', 'informationFlow',
 'Reportes de Cumplimiento y Calidad',
 'Compliance & Quality Reports',
 'Generación automática de reportes para acreditaciones, indicadores de calidad y cumplimiento regulatorio. Siempre listo para auditorías.',
 'Automatic report generation for accreditations, quality indicators, and regulatory compliance. Always audit-ready.',
 '2-3', 0.12, 3),

('medical', 'growthFlow',
 'Portal de Pacientes y Telemedicina',
 'Patient Portal & Telemedicine',
 'Plataforma digital para pacientes con acceso a resultados, citas y consultas virtuales. Expande capacidad de atención sin ampliar espacio físico.',
 'Digital platform for patients with access to results, appointments, and virtual consultations. Expands care capacity without expanding physical space.',
 '4-6', 0.20, 1),
('medical', 'growthFlow',
 'Marketing Médico y Presencia Digital',
 'Medical Marketing & Digital Presence',
 'SEO médico local, gestión de reputación en línea y contenido educativo que posiciona al doctor como referente. Atrae nuevos pacientes orgánicamente.',
 'Local medical SEO, online reputation management, and educational content that positions the doctor as an authority. Attracts new patients organically.',
 '3-4', 0.15, 2),
('medical', 'growthFlow',
 'Modelo de Atención Preventiva',
 'Preventive Care Model',
 'Programas de chequeo preventivo automatizados, recordatorios anuales y paquetes de salud. Genera ingresos recurrentes y mejora outcomes de pacientes.',
 'Automated preventive checkup programs, annual reminders, and health packages. Generates recurring revenue and improves patient outcomes.',
 '4-6', 0.18, 3);


-- ============================================================
-- LEGAL
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

('legal', 'customerFlow',
 'Bot de Consultas Legales Iniciales',
 'Initial Legal Consultation Bot',
 'Respuesta automática a consultas frecuentes, pre-calificación de casos y agendamiento de consultas. Filtra prospectos antes de consumir tiempo del abogado.',
 'Automatic responses to common questions, case pre-qualification, and consultation scheduling. Filters prospects before consuming attorney time.',
 '2-3', 0.30, 1),
('legal', 'customerFlow',
 'Portal de Clientes con Estado de Caso',
 'Client Portal with Case Status',
 'Acceso 24/7 al estado del caso, documentos compartidos y mensajería segura. Reduce llamadas de seguimiento un 60% y mejora satisfacción del cliente.',
 '24/7 access to case status, shared documents, and secure messaging. Reduces follow-up calls by 60% and improves client satisfaction.',
 '3-4', 0.20, 2),
('legal', 'customerFlow',
 'Onboarding Digital de Nuevos Clientes',
 'Digital New Client Onboarding',
 'Formularios de intake digitales, recopilación automatizada de documentos y firma electrónica de retainer. Reduce tiempo de apertura de caso un 50%.',
 'Digital intake forms, automated document collection, and electronic retainer signing. Reduces case opening time by 50%.',
 '2-3', 0.18, 3),

('legal', 'operationsFlow',
 'Automatización de Documentos y Seguimiento de Casos',
 'Document Automation & Case Tracking',
 'Generación automatizada de documentos legales, seguimiento de plazos y gestión de casos. Reduce horas de trabajo administrativo por caso.',
 'Automated legal document generation, deadline tracking, and case management. Reduces administrative hours per case.',
 '3-5', 0.35, 1),
('legal', 'operationsFlow',
 'Control de Tiempo y Facturación Automatizada',
 'Automated Time Tracking & Billing',
 'Registro automático de tiempo facturable, generación de facturas y seguimiento de cobros. Recupera un 15-20% de tiempo facturable que se pierde en tracking manual.',
 'Automatic billable time logging, invoice generation, and collections tracking. Recovers 15-20% of billable time lost to manual tracking.',
 '2-3', 0.25, 2),
('legal', 'operationsFlow',
 'Gestión de Plazos y Calendario Legal',
 'Deadline & Legal Calendar Management',
 'Seguimiento automático de plazos legales, alertas escalonadas y sincronización con calendarios. Nunca más pierdas un plazo de tribunal.',
 'Automatic legal deadline tracking, escalating alerts, and calendar sync. Never miss a court deadline again.',
 '1-2', 0.15, 3),

('legal', 'informationFlow',
 'Dashboard de Productividad y Rentabilidad por Caso',
 'Productivity & Case Profitability Dashboard',
 'Visibilidad de horas facturables, rentabilidad por tipo de caso y carga de trabajo por abogado. Optimiza la asignación de recursos del bufete.',
 'Visibility into billable hours, profitability by case type, and workload per attorney. Optimizes firm resource allocation.',
 '2-3', 0.25, 1),
('legal', 'informationFlow',
 'Análisis de Win Rate y Tipos de Caso',
 'Win Rate & Case Type Analytics',
 'Seguimiento de resultados por tipo de caso, abogado asignado y tribunal. Identifica las áreas de práctica más rentables y exitosas.',
 'Case outcome tracking by case type, assigned attorney, and court. Identifies the most profitable and successful practice areas.',
 '2-3', 0.15, 2),
('legal', 'informationFlow',
 'Reportes de Cumplimiento Ético',
 'Ethics Compliance Reports',
 'Monitoreo automático de conflictos de interés, trust accounting y cumplimiento con reglas del colegio de abogados. Protección proactiva.',
 'Automatic conflict of interest monitoring, trust accounting, and bar association compliance. Proactive protection.',
 '2-3', 0.12, 3),

('legal', 'growthFlow',
 'Sistema de Referidos y Marketing Legal Digital',
 'Referral System & Digital Legal Marketing',
 'Automatización de seguimiento a referidos, presencia digital optimizada y contenido legal educativo que genera confianza y atrae nuevos clientes.',
 'Automated referral follow-up, optimized digital presence, and educational legal content that builds trust and attracts new clients.',
 '4-6', 0.20, 1),
('legal', 'growthFlow',
 'Expansión de Áreas de Práctica',
 'Practice Area Expansion',
 'Análisis de demanda legal local, identificación de áreas de práctica desatendidas y templates para nuevos servicios. Crece el bufete estratégicamente.',
 'Local legal demand analysis, underserved practice area identification, and templates for new services. Grow the firm strategically.',
 '4-6', 0.15, 2),
('legal', 'growthFlow',
 'Plataforma de Servicios Legales Escalables',
 'Scalable Legal Services Platform',
 'Paquetes de servicios estandarizados para casos comunes (incorporaciones, contratos, marcas). Genera ingresos predecibles y escala sin más abogados.',
 'Standardized service packages for common cases (incorporations, contracts, trademarks). Generates predictable revenue and scales without more attorneys.',
 '6-8', 0.18, 3);


-- ============================================================
-- LOGISTICS
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

('logistics', 'customerFlow',
 'Tracking Automatizado y Notificaciones',
 'Automated Tracking & Notifications',
 'Actualizaciones automáticas de estado de envío por WhatsApp y web. Reduce llamadas de seguimiento y mejora la experiencia del cliente.',
 'Automatic shipment status updates via WhatsApp and web. Reduces follow-up calls and improves customer experience.',
 '2-3', 0.30, 1),
('logistics', 'customerFlow',
 'Portal de Cotizaciones Instantáneas',
 'Instant Quoting Portal',
 'Cotizador automático basado en origen, destino, peso y tipo de carga. El cliente obtiene precio al instante sin esperar a que alguien calcule manualmente.',
 'Automatic quoting based on origin, destination, weight, and cargo type. Customer gets instant pricing without waiting for manual calculations.',
 '2-3', 0.20, 2),
('logistics', 'customerFlow',
 'Gestión de Reclamos y Devoluciones',
 'Claims & Returns Management',
 'Sistema automatizado de reclamos con tracking, fotos de evidencia y resolución guiada. Reduce tiempo de resolución un 50% y mejora retención.',
 'Automated claims system with tracking, evidence photos, and guided resolution. Reduces resolution time by 50% and improves retention.',
 '3-4', 0.15, 3),

('logistics', 'operationsFlow',
 'Optimización de Rutas y Despacho',
 'Route Optimization & Dispatch',
 'Planificación automática de rutas, asignación inteligente de conductores y seguimiento en tiempo real. Reduce costos de combustible y mejora entregas a tiempo.',
 'Automatic route planning, intelligent driver assignment, and real-time tracking. Reduces fuel costs and improves on-time deliveries.',
 '4-6', 0.40, 1),
('logistics', 'operationsFlow',
 'Gestión de Almacén Automatizada',
 'Automated Warehouse Management',
 'Control de ubicaciones, picking optimizado, recepción digital de mercancía y control de inventario en tiempo real. Reduce errores de despacho un 80%.',
 'Location control, optimized picking, digital receiving, and real-time inventory tracking. Reduces dispatch errors by 80%.',
 '4-6', 0.30, 2),
('logistics', 'operationsFlow',
 'Mantenimiento Preventivo de Flota',
 'Preventive Fleet Maintenance',
 'Programación automática de mantenimiento basada en kilometraje y horas de uso. Alertas de servicio, historial de reparaciones y control de costos por vehículo.',
 'Automatic maintenance scheduling based on mileage and usage hours. Service alerts, repair history, and per-vehicle cost tracking.',
 '2-3', 0.20, 3),

('logistics', 'informationFlow',
 'Dashboard de Flota y Rendimiento Operativo',
 'Fleet & Operations Performance Dashboard',
 'Métricas de entregas, tiempos de ruta, utilización de flota y costos por entrega. Identifica cuellos de botella y optimiza la operación.',
 'Delivery metrics, route times, fleet utilization, and cost per delivery. Identifies bottlenecks and optimizes operations.',
 '2-3', 0.25, 1),
('logistics', 'informationFlow',
 'Análisis de Última Milla',
 'Last-Mile Analytics',
 'Datos detallados de la última milla: tiempos de entrega, intentos fallidos, zonas problemáticas y satisfacción por área. Optimiza lo más costoso del proceso.',
 'Detailed last-mile data: delivery times, failed attempts, problem zones, and satisfaction by area. Optimizes the most expensive part of the process.',
 '2-3', 0.18, 2),
('logistics', 'informationFlow',
 'Reportes de Cumplimiento y SLA',
 'Compliance & SLA Reports',
 'Monitoreo automático de SLAs por cliente, reportes de cumplimiento y alertas de desviación. Protege contratos y demuestra valor al cliente.',
 'Automatic SLA monitoring per client, compliance reports, and deviation alerts. Protects contracts and demonstrates value to clients.',
 '1-2', 0.15, 3),

('logistics', 'growthFlow',
 'Plataforma de Capacidad y Nuevas Rutas',
 'Capacity Planning & Route Expansion Platform',
 'Análisis de demanda, planificación de capacidad y expansión de cobertura basada en datos. Escala la operación sin duplicar costos fijos.',
 'Demand analysis, capacity planning, and data-driven coverage expansion. Scale operations without doubling fixed costs.',
 '4-6', 0.20, 1),
('logistics', 'growthFlow',
 'Marketplace de Carga Colaborativa',
 'Collaborative Freight Marketplace',
 'Plataforma para consolidar carga entre clientes, optimizar viajes de retorno y compartir capacidad. Reduce costos y aumenta utilización de flota.',
 'Platform to consolidate cargo between clients, optimize return trips, and share capacity. Reduces costs and increases fleet utilization.',
 '6-8', 0.18, 2),
('logistics', 'growthFlow',
 'Integración con E-commerce y 3PL',
 'E-commerce & 3PL Integration',
 'APIs de integración con Shopify, WooCommerce y plataformas de e-commerce. Posiciona tu empresa como fulfillment partner de tiendas en línea.',
 'Integration APIs with Shopify, WooCommerce, and e-commerce platforms. Positions your company as an online store fulfillment partner.',
 '4-6', 0.22, 3);


-- ============================================================
-- CONSTRUCTION
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

('construction', 'customerFlow',
 'Portal de Clientes y Cotizaciones Automatizadas',
 'Client Portal & Automated Quotes',
 'Cotizaciones automáticas basadas en especificaciones, portal de seguimiento de proyecto para clientes y comunicación centralizada. Reduce ida y vuelta de emails.',
 'Automatic quotes based on specs, project tracking portal for clients, and centralized communication. Reduces back-and-forth emails.',
 '3-4', 0.25, 1),
('construction', 'customerFlow',
 'Reportes de Progreso Visuales Automatizados',
 'Automated Visual Progress Reports',
 'Reportes semanales automáticos con fotos del avance, porcentaje completado y próximos hitos. El cliente siempre sabe cómo va su proyecto.',
 'Automatic weekly reports with progress photos, completion percentage, and upcoming milestones. Clients always know how their project is going.',
 '2-3', 0.15, 2),
('construction', 'customerFlow',
 'Sistema de Garantías y Post-Entrega',
 'Warranty & Post-Delivery System',
 'Seguimiento automatizado de garantías, reclamos post-entrega y mantenimiento preventivo. Genera confianza y referidos de clientes satisfechos.',
 'Automated warranty tracking, post-delivery claims, and preventive maintenance. Builds trust and referrals from satisfied clients.',
 '2-3', 0.12, 3),

('construction', 'operationsFlow',
 'Gestión de Proyectos y Control de Costos',
 'Project Management & Cost Control',
 'Seguimiento automatizado de progreso, control de materiales, gestión de subcontratistas y alertas de desviación presupuestaria. Reduce sobrecostos.',
 'Automated progress tracking, materials control, subcontractor management, and budget deviation alerts. Reduces cost overruns.',
 '4-6', 0.35, 1),
('construction', 'operationsFlow',
 'Control de Materiales y Compras',
 'Materials & Procurement Control',
 'Gestión centralizada de compras, comparación de proveedores, control de entregas y seguimiento de precios. Reduce costos de materiales un 8-15%.',
 'Centralized procurement management, supplier comparison, delivery tracking, and price monitoring. Reduces material costs by 8-15%.',
 '3-4', 0.22, 2),
('construction', 'operationsFlow',
 'Seguridad y Cumplimiento en Obra',
 'Site Safety & Compliance',
 'Checklists digitales de seguridad, registro de incidentes, capacitaciones automatizadas y reportes OSHA. Reduce riesgo de multas y accidentes.',
 'Digital safety checklists, incident logging, automated training, and OSHA reporting. Reduces risk of fines and accidents.',
 '2-3', 0.15, 3),

('construction', 'informationFlow',
 'Dashboard de Proyectos y Rentabilidad',
 'Project & Profitability Dashboard',
 'Visibilidad de costos reales vs. presupuesto, avance por proyecto, productividad de cuadrillas y cash flow proyectado. Decisiones financieras informadas.',
 'Visibility into actual vs. budgeted costs, project progress, crew productivity, and projected cash flow. Informed financial decisions.',
 '3-4', 0.25, 1),
('construction', 'informationFlow',
 'Análisis de Productividad por Cuadrilla',
 'Crew Productivity Analytics',
 'Métricas de rendimiento por cuadrilla, comparativas entre proyectos y análisis de factores que afectan productividad. Optimiza asignación de personal.',
 'Performance metrics per crew, cross-project comparisons, and analysis of productivity factors. Optimizes staff allocation.',
 '2-3', 0.18, 2),
('construction', 'informationFlow',
 'Forecasting de Cash Flow por Proyecto',
 'Per-Project Cash Flow Forecasting',
 'Proyecciones automáticas de flujo de caja por proyecto y consolidado. Anticipa necesidades de capital y evita cuellos de botella financieros.',
 'Automatic cash flow projections per project and consolidated. Anticipates capital needs and avoids financial bottlenecks.',
 '2-3', 0.15, 3),

('construction', 'growthFlow',
 'Sistema de Licitaciones y Pipeline de Proyectos',
 'Bid Management & Project Pipeline System',
 'Gestión automatizada de licitaciones, seguimiento de pipeline y análisis de capacidad para tomar más proyectos sin perder calidad de ejecución.',
 'Automated bid management, pipeline tracking, and capacity analysis to take on more projects without sacrificing execution quality.',
 '5-8', 0.20, 1),
('construction', 'growthFlow',
 'Pre-calificación y Scoring de Proyectos',
 'Project Pre-qualification & Scoring',
 'Evaluación automática de oportunidades basada en rentabilidad histórica, riesgo, capacidad y alineación estratégica. Toma solo los proyectos que convienen.',
 'Automatic opportunity evaluation based on historical profitability, risk, capacity, and strategic alignment. Take only the projects that make sense.',
 '3-4', 0.15, 2),
('construction', 'growthFlow',
 'Certificaciones y Acceso a Contratos Gubernamentales',
 'Certifications & Government Contract Access',
 'Gestión de certificaciones (HUBZone, SBA 8a, DBE), seguimiento de renovaciones y acceso a oportunidades de contratos gubernamentales en PR.',
 'Certification management (HUBZone, SBA 8a, DBE), renewal tracking, and access to government contract opportunities in PR.',
 '4-6', 0.18, 3);


-- ============================================================
-- RETAIL
-- ============================================================

INSERT INTO solutions (industry, stream, name_es, name_en, description_es, description_en, implementation_time, savings_pct, priority) VALUES

('retail', 'customerFlow',
 'Asistente de Ventas con IA y WhatsApp Commerce',
 'AI Sales Assistant & WhatsApp Commerce',
 'Catálogo digital por WhatsApp, recomendaciones personalizadas y procesamiento de pedidos 24/7. Convierte consultas en ventas incluso fuera de horario.',
 'Digital catalog via WhatsApp, personalized recommendations, and 24/7 order processing. Converts inquiries into sales even after hours.',
 '2-3', 0.35, 1),
('retail', 'customerFlow',
 'Programa de Lealtad y Recompensas',
 'Loyalty & Rewards Program',
 'Sistema de puntos digital, ofertas personalizadas y comunicación automatizada basada en historial de compras. Aumenta frecuencia de visita un 25%.',
 'Digital points system, personalized offers, and automated communication based on purchase history. Increases visit frequency by 25%.',
 '2-3', 0.20, 2),
('retail', 'customerFlow',
 'Gestión de Reseñas y Reputación',
 'Review & Reputation Management',
 'Solicitud automática de reseñas post-compra, gestión de feedback negativo y monitoreo de reputación en línea. Convierte compradores en promotores.',
 'Automatic post-purchase review requests, negative feedback management, and online reputation monitoring. Turns buyers into promoters.',
 '1-2', 0.12, 3),

('retail', 'operationsFlow',
 'Gestión Inteligente de Inventario',
 'Smart Inventory Management',
 'Control automático de stock, alertas de reorden, análisis de rotación y sincronización multi-canal. Elimina quiebres de inventario y sobrestock.',
 'Automatic stock control, reorder alerts, turnover analysis, and multi-channel sync. Eliminates stockouts and overstock.',
 '3-5', 0.40, 1),
('retail', 'operationsFlow',
 'POS Integrado y Conciliación Automática',
 'Integrated POS & Auto Reconciliation',
 'Sistema de punto de venta conectado con inventario, contabilidad y reportes. Conciliación automática de caja diaria. Cero discrepancias.',
 'Point-of-sale system connected with inventory, accounting, and reports. Automatic daily cash reconciliation. Zero discrepancies.',
 '2-3', 0.25, 2),
('retail', 'operationsFlow',
 'Gestión de Proveedores y Compras',
 'Supplier & Procurement Management',
 'Evaluación de proveedores, órdenes de compra automatizadas y seguimiento de entregas. Negocia mejores precios con datos de volumen histórico.',
 'Supplier evaluation, automated purchase orders, and delivery tracking. Negotiate better prices with historical volume data.',
 '2-3', 0.18, 3),

('retail', 'informationFlow',
 'Dashboard de Ventas y Comportamiento del Cliente',
 'Sales & Customer Behavior Dashboard',
 'Análisis de ventas por producto, hora y canal. Patrones de compra, ticket promedio y métricas de conversión para optimizar surtido y promociones.',
 'Sales analysis by product, time, and channel. Purchase patterns, average ticket, and conversion metrics to optimize assortment and promotions.',
 '2-3', 0.25, 1),
('retail', 'informationFlow',
 'Análisis de Surtido y Planograma',
 'Assortment & Planogram Analytics',
 'Optimización automática de surtido basada en rentabilidad, rotación y demanda. Maximiza ventas por metro cuadrado de estante.',
 'Automatic assortment optimization based on profitability, turnover, and demand. Maximizes sales per square foot of shelf space.',
 '2-3', 0.18, 2),
('retail', 'informationFlow',
 'Análisis de Tráfico y Conversión en Tienda',
 'In-Store Traffic & Conversion Analytics',
 'Conteo de visitantes, análisis de zonas calientes, tasa de conversión y correlación con promociones. Entiende el comportamiento real en tu tienda.',
 'Visitor counting, hot zone analysis, conversion rate, and promotion correlation. Understand real behavior in your store.',
 '3-4', 0.15, 3),

('retail', 'growthFlow',
 'E-commerce y Marketing Automatizado',
 'E-commerce & Automated Marketing',
 'Tienda en línea integrada con inventario, campañas automatizadas basadas en comportamiento de compra y programa de fidelización para escalar ventas.',
 'Online store integrated with inventory, behavior-based automated campaigns, and loyalty program to scale sales.',
 '4-6', 0.20, 1),
('retail', 'growthFlow',
 'Expansión Omnicanal',
 'Omnichannel Expansion',
 'Presencia integrada en marketplace (Amazon, eBay), redes sociales y tienda física. Inventario sincronizado y experiencia de compra unificada.',
 'Integrated presence on marketplaces (Amazon, eBay), social media, and physical store. Synced inventory and unified shopping experience.',
 '4-6', 0.22, 2),
('retail', 'growthFlow',
 'Análisis de Nuevas Ubicaciones',
 'New Location Analysis',
 'Evaluación basada en datos de potenciales nuevas ubicaciones: demografía, competencia, tráfico y proyección de ventas. Abre tiendas con confianza.',
 'Data-driven evaluation of potential new locations: demographics, competition, traffic, and sales projections. Open stores with confidence.',
 '3-4', 0.15, 3);
